@SimulaBank.API_HostAddress = http://localhost:5232/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJJbnZldHN0b3JDbGllbnRlIiwidXNlciI6IntcIkNwZlwiOlwiMDc2MDE0OTk1MDJcIixcIkVtYWlsXCI6XCJsaXNhbmRyYWdvbWVzNTNAZ21haWwuY29tXCIsXCJBdXRob3JpemVkXCI6ZmFsc2V9Iiwicm9sZSI6IntcIklkXCI6XCIyXCIsXCJEZXNjcmlwdGlvblwiOlwiSW52ZXRzdG9yQ2xpZW50ZVwifSIsInBlcm1pc3Npb25zIjoiW10iLCJleHAiOjE3NzQyMDEzNjUsImlzcyI6IlNpbXVsYUJhbmsuQVBJIiwiYXVkIjoiU2ltdWxhQmFuay5BUEkgQ29yZSJ9.38HBbcOYQ4m6d4PZbNPOoz1KIo7clS0V6goF68y1J8
###

POST {{SimulaBank.API_HostAddress}}/User/Register
Accept: application/json
Content-Type: application/json
{
  "name": "Lisandra",
  "midName": "Bomfim",
  "email": "lisandragomes53@gmail.com",
  "cpf": "07601499502",
  "birthDate": "23/07/2000",
  "password": "simula@bank",
  "idTipoUsuario": 2,
  "userMaster": true
}

###

POST {{SimulaBank.API_HostAddress}}/Autenthication
Accept: application/json
Content-type: application/json

{
  "login":"07601499502",
  "password":"simula@bank",
  "tokenRefreshOrAcess": "string"
}

###

POST {{SimulaBank.API_HostAddress}}/Bank/Create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "title": "Comprar Terreno",
  "description": "",
  "goalValue": 100000,
  "idealCurrentValue": 4167,
  "currentValue": 0,
  "status": 1,
  "createDate": "2026-03-21T17:53:38.301Z",
  "monthOfDeadline": 0,
  "dueDate": "2028-03-21T17:53:38.301Z",
  "valueAutoDeductValueAccount": 0,
  "dayAutoDeductValueAccount": 0,
  "idUser": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

