@SimulaBank.API_HostAddress = https://localhost:5232/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJJbnZldHN0b3JDbGllbnRlIiwidXNlciI6IntcIkNwZlwiOlwiMDc2MDE0OTk1MDJcIixcIkVtYWlsXCI6XCJsaXNhbmRyYWdvbWVzNTNAZ21haWwuY29tXCIsXCJBdXRob3JpemVkXCI6ZmFsc2V9Iiwicm9sZUpzb24iOiJ7XCJJZFwiOlwiMlwiLFwiRGVzY3JpcHRpb25cIjpcIkludmV0c3RvckNsaWVudGVcIn0iLCJwZXJtaXNzaW9ucyI6IltdIiwiZXhwIjoxNzc0MzIwMTk1LCJpc3MiOiJTaW11bGFCYW5rLkFQSSIsImF1ZCI6IlNpbXVsYUJhbmsuQVBJIENvcmUifQ.ZBL3f6IKqf2gngETO0SqsuM_d4A0XZutqezlou0AOFk
@idUser = d58683c9-4162-4a42-956b-f2426d86b9d8
@idPiggy = dc551014-6500-4711-bb9b-e433bb909b49
###

POST {{SimulaBank.API_HostAddress}}/User/Register
Accept: application/json
Content-Type: application/json
{
  "name": "Lisandra",
  "midName": "Bomfim",
  "email": "lisandragomes53@gmail.com",
  "cpf": "07601499502",
  "birthDate": "23/07/2000",
  "password": "simula@bank",
  "idTipoUsuario": 2,
  "userMaster": true
}

###

POST {{SimulaBank.API_HostAddress}}/Autenthication
Accept: application/json
Content-type: application/json

{
  "login":"07601499502",
  "password":"simula@bank",
  "tokenRefreshOrAcess": "string"
}

###
 
POST {{SimulaBank.API_HostAddress}}/Bank/Create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "title": "Comprar Terreno",
  "description": "",
  "goalValue": 100000,
  "idealCurrentValue": 4167,
  "currentValue": 0,
  "status": 1,
  "createDate": "2026-03-21T17:53:38.301Z",
  "monthOfDeadline": 0,
  "dueDate": "2028-03-21T17:53:38.301Z",
  "valueAutoDeductValueAccount": 0,
  "dayAutoDeductValueAccount": 0,
  "idUser": "{{idUser}}"
}

###
@onlyActive = true
GET {{SimulaBank.API_HostAddress}}/Bank/User/{{idUser}}/{{onlyActive}}
Authorization: Bearer {{token}}

###

GET {{SimulaBank.API_HostAddress}}/Bank/{{idPiggy}}
Authorization: Bearer {{token}}

###
PUT {{SimulaBank.API_HostAddress}}/Bank/{{idPiggy}}
Authorization: Bearer {{token}}

###

@idPiggyDelete = dc551014-6500-4711-bb9b-e433bb909b49
DELETE {{SimulaBank.API_HostAddress}}/Bank/{{idPiggyDelete}}
Authorization: Bearer {{token}}

###
